SOURCES = [
    {
        "id": "nejm",
        "name": "NEJM",
        "full_name": "New England Journal of Medicine",
        "daily_url": "https://www.nejm.org/most-read?period=day",
        "weekly_url": "https://www.nejm.org/most-read?period=week",
        "monthly_url": "https://www.nejm.org/most-read?period=month",
        "type": "journal",
    },
    {
        "id": "jco",
        "name": "JCO",
        "full_name": "Journal of Clinical Oncology",
        "daily_url": "https://ascopubs.org/action/showMostReadArticles?journal=jco&period=day",
        "weekly_url": "https://ascopubs.org/action/showMostReadArticles?journal=jco&period=week",
        "monthly_url": "https://ascopubs.org/action/showMostReadArticles?journal=jco&period=month",
        "type": "journal",
    },
    {
        "id": "lancet_oncology",
        "name": "Lancet Oncology",
        "full_name": "The Lancet Oncology",
        "daily_url": "https://www.thelancet.com/journals/lanonc/issue/current",
        "weekly_url": "https://www.thelancet.com/journals/lanonc/most-read",
        "monthly_url": "https://www.thelancet.com/journals/lanonc/most-read",
        "type": "journal",
    },
    {
        "id": "nature_cancer",
        "name": "Nature Cancer",
        "full_name": "Nature Cancer",
        "daily_url": "https://www.nature.com/natcancer/research-articles",
        "weekly_url": "https://www.nature.com/natcancer/research-articles",
        "monthly_url": "https://www.nature.com/natcancer/research-articles",
        "type": "journal",
    },
    {
        "id": "asco",
        "name": "ASCO",
        "full_name": "American Society of Clinical Oncology",
        "daily_url": "https://www.asco.org/news-initiatives/current-asco-news",
        "weekly_url": "https://www.asco.org/news-initiatives/current-asco-news",
        "monthly_url": "https://www.asco.org/news-initiatives/current-asco-news",
        "type": "society",
    },
    {
        "id": "esmo",
        "name": "ESMO",
        "full_name": "European Society for Medical Oncology",
        "daily_url": "https://www.esmo.org/oncology-news",
        "weekly_url": "https://www.esmo.org/oncology-news",
        "monthly_url": "https://www.esmo.org/oncology-news",
        "type": "society",
    },
    {
        "id": "cancer_discovery",
        "name": "Cancer Discovery",
        "full_name": "Cancer Discovery (AACR)",
        "daily_url": "https://aacrjournals.org/cancerdiscovery/most-read",
        "weekly_url": "https://aacrjournals.org/cancerdiscovery/most-read",
        "monthly_url": "https://aacrjournals.org/cancerdiscovery/most-read",
        "type": "journal",
    },
]
